---
- name: "setup directory {{item.path}}"
  file:
    path: "{{item.path}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
    state: "directory"
    recurse: "yes"
  when: item.state != 'absent'

- name: "setup mount {{item.path}} {{item.opts}}"
  mount:
    path: "{{item.path}}"
    src: "{{item.src}}"
    fstype: "{{item.fstype}}"
    opts: "{{item.opts}}"
    state: "{{item.state}}"
  when: item.state != 'absent'

- name: "absent directory {{item.path}}"
  file:
    path: "{{item.path}}"
    state: "absent"
  when: item.state == 'absent'

- name: "absent mount {{item.path}} {{item.opts}}"
  mount:
    path: "{{item.path}}"
    src: "{{item.src}}"
    state: "absent"
  when: item.state == 'absent'
